### ISSUE TITLE
How to generate more than 100 thumbnails 

### ISSUE THREAD

**Issue by CXwudi** [fanta-git/re-align-thumbnail#25]
Hi,

Thanks for making this amazing website with the support for VocaDB.

I have a list in VocaDB with 170+ songs, and I set 20 rows and 10 columns, but the website only generate first 100 thumbnails and the rest of space is blank.

![Screenshot_20230729-135253](https://github.com/fanta-git/re-align-thumbnail/assets/17377423/31a39556-adac-4bf8-b5cd-5d2b886505c0)

I wondering is it a bug? Or did I do something wrong?

**Comment by fanta-git** [comment]
Thanks for the report.
This is a bug! I will fix it.
